@API_HostAddress = https://jumpinevents.azurewebsites.net/

GET {{API_HostAddress}}/pogoda/
Accept: application/json
###

GET {{API_HostAddress}}/api/activities
Accept: application/json

###
