name: Build and deploy ASP.Net Core app to Azure Web App - jumpin-events

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Step to setup Node.js for React app build
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you need

      # Step to install dependencies and build the React app
      - name: Install and build React app
        run: |
          cd client-app/frontWeb  # Adjust this to the path of your React app relative to the root of your repository
          npm install
          sudo npm run build

      # Step to copy the React build output to the .NET Core app's wwwroot directory
      - name: Copy React build to .NET wwwroot
        run: |
          Copy-Item -Path "client-app/frontWeb" -Destination "site/wwwroot/" -Recurse -Force
  # Adjust the source and destination paths as needed

      # Continue with the existing .NET setup and build steps
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Existing steps to upload the artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # The deploy job remains unchanged
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jumpin-events'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0BCAA840C428488B901A0ED00819E9DC }}
          package: .
