name: Build and deploy ASP.Net Core app to Azure Web App - jumpinevents

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Step to setup Node.js for React app build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you need

      # Step to install dependencies and build the React app
      - name: Install and build React app
        run: |
          cd client-app/frontWeb  # Adjust this to the path of your React app relative to the root of your repository
          npm install
          npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: client-app/frontWeb/site/wwwroot
      # Step to copy the React build output to the .NET Core app's wwwroot directory
  #    - name: Copy React build to .NET wwwroot
 #       run: |
#          Copy-Item -Path "API/reactivities.db" -Destination "/home/site/wwwroot" -Recurse -Force
  # Adjust the source and destination paths as needed

      # Continue with the existing .NET setup and build steps
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Existing steps to upload the artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # The deploy job remains unchanged
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7352FD2C3252475CB7DDA9656DA27273 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87B246C660A149FCBBA8519C60B4E64D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4F17F97B1D014D37A6CD0C80D2792F7F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jumpinevents'
          slot-name: 'Production'
          package: .
